import { Inter } from "next/font/google";
import "./globals.css";


import Header from "./components/Header/page";
import Footer from "./components/Footer/page";
import Homepage from "./components/Homepage/page";
import AboutUs from "./components/Aboutus/page";
import ProductService1 from "./components/ProductService1/page";
import ProductService2 from "./components/ProductService2/page";
import TeamPages from "./components/TeamPages/page";
import Body from "./components/Body/page";

// import Footer from "./components/Footer";
// import Header from "./components/Header";
// import Carousel from "./components/Carousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Homepage />
        <AboutUs />
        <ProductService1 />
        <ProductService2 />
        <TeamPages />
        <Body />
        <main className="container mx-auto pt-20 min-h-screen">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
